sudo: required

services:
  - docker

language: node_js

node_js:
  - node

# cache:
#   bundler: true
#   directories:
#     - node_modules
#     - $HOME/docker

# before_cache:
#   # Save tagged docker images
#   - >
#     mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#     | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

# before_install:
#   # Load cached docker images
#   - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - npm install
  - docker-compose -f tests/docker/docker-compose.test.yml build yayata >/dev/null
  - docker-compose -f tests/docker/docker-compose.test.yml build ninetofiver >/dev/null
  - docker-compose -f tests/docker/docker-compose.test.yml build cypress >/dev/null


script:
  - docker-compose -f tests/docker/docker-compose.test.yml run cypress